Downgrade glog to make theia build successfully
Not sure if I need to go this far back -- I went to the oldest
version available in conda. Error was:

/projects/BinaryBuilder/build_asp/install/include/glog/logging.h:695: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'